import { SpellShadowdark } from "../../interfaces/CharacterShadowdark";

const SPELLS_SD: Omit<SpellShadowdark, 'id'>[] = [
    {
        name: 'Acid Arrow',
        tier: 2,
        range: 'Far',
        duration: 'Focus',
        description: 'You conjure a corrosive bolt that hits one foe, dealing 1d6 damage a round. The bolt remains in the target for as long as you focus.',
        class: 'Wizard'
    },
    {
        name: 'Alarm',
        tier: 1,
        range: 'Close',
        duration: '1 day',
        description: 'You touch one object, such as a door threshold, setting a magical alarm on it. If any creature you do not designate while casting the spell touches or crosses past the object, a magical bell sounds in your head.',
        class: 'Wizard'
    },
    {
        name: 'Alter Self',
        tier: 2,
        range: 'Self',
        duration: '5 rounds',
        description: 'You magically change your physical form, gaining one feature that modifies your existing anatomy. For example, you can grow functional gills on your neck or bear claws on your fingers. This spell can’t grow wings or limbs.',
        class: 'Wizard'
    },
    {
        name: 'Augury',
        tier: 2,
        range: 'Self',
        duration: 'Instant',
        description: 'You interpret the meaning of supernatural portents and omens. Ask the GM one question about a specific course of action. The GM says whether the action will lead to “weal” or “woe.”',
        class: 'Priest'
    },
    {
        name: 'Bless',
        tier: 2,
        range: 'Close',
        duration: 'Instant',
        description: 'One creature you touch gains a luck token.',
        class: 'Priest'
    },
    {
        name: 'Blind/Deafen',
        tier: 2,
        range: 'Near',
        duration: 'Focus',
        description: 'You utter a divine censure,\nblinding or deafening one\ncreature you can see in range.\nThe creature has disadvantage\non tasks requiring the lost sense.',
        class: 'Priest'
    },
    {
        name: 'Burning Hands',
        tier: 1,
        class: 'Wizard',
        duration: 'Instant',
        range: 'Close',
        description: 'You spread your fingers with thumbs touching, unleashing a circle of flame that fills a close area around where you stand. Creatures within the area of effect take 1d6 damage. Unattended flammable objects ignite.'
    },
    {
        name: 'Charm Person',
        tier: 1,
        class: 'Wizard',
        duration: '1d8 days',
        range: 'Near',
        description: 'You magically beguile one humanoid of LV 2 or less within near range, who regards you as a friend for the duration. The spell ends if you or your allies do anything harmful to the target. The target knows it was magically charmed after the spell ends.'
    },
    {
        name: 'Cleansing Weapon',
        tier: 2,
        class: 'Priest',
        duration: '5 rounds',
        range: 'Close',
        description: 'One weapon you touch is wreathed in purifying flames. It deals an additional 1d4 damage (1d6 vs. undead) for the duration.'
    },
    {
        name: 'Cure Wounds',
        tier: 1,
        class: 'Priest',
        duration: 'Instant',
        range: 'Close',
        description: 'Your touch restores ebbing life. Roll a number of d6s equal to 1 + half your level (rounded down). One target you touch regains that many hit points.'
    },
    {
        name: 'Detect Magic',
        tier: 1,
        class: 'Wizard',
        duration: 'Focus',
        range: 'Near',
        description: `You can sense the presence of magic within near range for the spell's duration. If you focus for two rounds, you discern its general properties. Full barriers block this spell.`
    },
    {
        name: 'Detect Thoughts',
        tier: 2,
        class: 'Wizard',
        duration: 'Focus',
        range: 'Near',
        description: `You peer into the mind of one creature you can see within the spell's range. Each round, you learn the target's immediate thoughts. On its turn, the target makes a Wisdom check opposed by your last spellcasting check. If the target succeeds, it notices your presence in its mind and the spell ends.`
    },
    {
        name: 'Feather Fall',
        tier: 1,
        class: 'Wizard',
        duration: 'Instant',
        range: 'Self',
        description: `You may make an attempt to cast this spell when you fall. Your rate of descent slows so that you land safely on your feet.`,
    },
    {
        name: 'Fixed Object',
        tier: 2,
        class: 'Wizard',
        duration: '5 rounds',
        range: 'Close',
        description: `An object you touch that weighs no more than 5 pounds becomes fixed in its current location. It can support up to 5,000 pounds of weight for the duration of the spell.`,
    },
    {
        name: 'Floating Disk',
        tier: 1,
        class: 'Wizard',
        duration: '10 rounds',
        range: 'Near',
        description: `You create a floating, circular disk of force with a concave center. It can carry up to 20 gear slots. It hovers at waist level and automatically stays within near of you. It can't cross over dropoffs or pits taller than a human.`,
    },
    {
        name: 'Hold Person',
        tier: 2,
        class: 'Wizard',
        duration: 'Focus',
        range: 'Near',
        description: `You magically paralyze one human`,
    },
    {
        name: 'Hold Portal',
        tier: 1,
        class: 'Wizard',
        duration: '10 rounds',
        range: 'Near',
        description: `You magically hold a portal closed for the duration. A creature must make a successful STR check vs. your spellcasting check to open the portal. The knock spell ends this spell.`,
    },
    {
        name: 'Holy Weapon',
        tier: 1,
        class: 'Priest',
        duration: '5 rounds',
        range: 'Close',
        description: `One weapon you touch is imbued with a sacred blessing. The weapon becomes magical and has +1 to attack and damage rolls for the duration.`,
    },
    {
        name: 'Invisibility',
        tier: 2,
        class: 'Wizard',
        duration: '10 rounds',
        range: 'Close',
        description: `A creature you touch becomes invisible for the spell's duration. The spell ends if the target attacks or casts a spell.`,
    },
    {
        name: 'Knock',
        tier: 2,
        class: 'Wizard',
        duration: 'Instant',
        range: 'Near',
        description: `A door, window, gate, chest, or portal you can see within range instantly opens, defeating all mundane locks and barriers. This spell creates a loud knock`,
    },
    {
        name: 'Levitate',
        tier: 2,
        class: 'Wizard',
        duration: 'Focus',
        range: 'Self',
        description: `You can float a near distance vertically per round on your turn. You can also push against solid objects to move horizontally.`,
    },
    {
        name: 'Light',
        tier: 1,
        class: 'Priest',
        duration: '1 hour real time',
        range: 'Close',
        description: `One object you touch glows with bright, heatless light, illuminating out to a near distance for 1 hour of real time.`,
    },
    {
        name: 'Mage Armor',
        tier: 1,
        class: 'Wizard',
        duration: '10 rounds',
        range: 'Self',
        description: `An invisible layer of magical force protects your vitals. Your armor class becomes 14 (18 on a critical spellcasting check) for the spell's duration.`,
    },
    {
        name: 'Magic Missile',
        tier: 1,
        class: 'Wizard',
        duration: 'Instant',
        range: 'Far',
        description: `You have advantage on your check to cast this spell. A glowing bolt of force streaks from your open hand, dealing 1d4 damage to one target.`,
    },
    {
        name: 'Mirror Image',
        tier: 2,
        class: 'Wizard',
        duration: '5 rounds',
        range: 'Self',
        description: `You create a number of illusory duplicates of yourself equal to half your level rounded down (minimum 1). The duplicates surround you and mimic you. Each time a creature attacks you, the attack misses and causes one of the duplicates to evaporate. If all of the illusions have disappeared, the spell ends.`,
    },
    {
        name: 'Misty Step',
        tier: 2,
        class: 'Wizard',
        duration: 'Instant',
        range: 'Self',
        description: `In a puff of smoke, you teleport a near distance to an area you can see.`,
    },
    {
        name: 'Protection from Evil',
        tier: 1,
        class: 'Priest',
        duration: 'Focus',
        range: 'Close',
        description: `For the spell's duration, chaotic beings have disadvantage on attack rolls and hostile spellcasting checks against the target. These beings also can't possess, compel, or beguile it. When cast on an already possessed target, the possessing entity makes a CHA check vs. the last spellcasting check. On a failure, the entity is expelled.`,
    },
    {
        name: 'Shield of Faith',
        tier: 1,
        class: 'Priest',
        duration: '5 rounds',
        range: 'Self',
        description: `A protective force wrought of your holy conviction surrounds you. You gain a +2 bonus to your armor class for the duration.`,
    },
    {
        name: 'Silence',
        tier: 2,
        class: 'Wizard',
        duration: 'Focus',
        range: 'Far',
        description: `You magically mute sound in a near cube within the spell's range. Creatures inside the area are deafened, and any sounds they create cannot be heard.`,
    },
    {
        name: 'Sleep',
        tier: 1,
        class: 'Wizard',
        duration: 'Instant',
        range: 'Near',
        description: `This spell fills a near-sized cube extending from you. Choose a number of living creatures in the area up to your level. Those creatures fall into a deep sleep if they are LV 2 or less. Injury or vigorous shaking wakes them.`,
    },
    {
        name: 'Smite',
        tier: 2,
        class: 'Priest',
        duration: 'Instant',
        range: 'Near',
        description: `You call down punishing flames on a creature you can see within range. It takes 1d6 damage.`,
    },
    {
        name: 'Turn Undead',
        tier: 1,
        class: 'Priest',
        duration: 'Instant',
        range: 'Near',
        description: `You rebuke undead creatures, forcing them to flee. You must present a holy symbol to cast this spell. If you succeed, each undead creature within 30 feet of you must make a CHA check vs. your spellcasting check. On a failure, the creature flees from you for 1d4 rounds. If the creature is a skeleton, it is destroyed.`,
    },
    {
        name: 'Web',
        tier: 2,
        class: 'Wizard',
        duration: 'Focus',
        range: 'Far',
        description: `You conjure a sticky web in a near cube within range. The web fills the cube and remains for the spell's duration. Creatures in the web's area when you cast the spell must make a STR check vs. your spellcasting check. On a failure, the creature is restrained. A creature can use its action to make a STR check vs. your spellcasting check. On a success, it frees itself.`,
    },
    {
        name: 'Zone of Truth',
        tier: 2,
        class: 'Priest',
        duration: 'Focus',
        range: 'Close',
        description: `You create a magical zone that guards against deception in a near cube within range. Creatures in the area when you cast the spell must make a CHA check vs. your spellcasting check. On a failure, a creature can't speak a deliberate lie while in the zone. You know which creatures fail their saving throws.`,
    }    
]

export default SPELLS_SD;