import { Attack } from "../../interfaces/Character";

export const WEAPON_STATS: Record<string, Partial<Attack>> = {
    'Club': {
        atk_ability: 'STR', // e.g. STR
        range: '',
        dmg_die: '1d4', // e.g. 1d6
        dmg_ability: 'STR', // e.g. STR
        dmg_type: 'Bludgeoning', // e.g. Slashing
        versatile_die: '',
    },
    'Dagger': {
        atk_ability: 'DEX',
        range: '20/60',
        dmg_die: '1d4', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing', 
        versatile_die: '',
    },
    'Greatclub': {
        atk_ability: 'STR',
        range: '',
        dmg_die: '1d8',
        dmg_ability: 'STR',
        dmg_type: 'Bludgeoning',
        versatile_die: '',
    },
    'Handaxe': {
        atk_ability: 'STR', 
        range: '20/60',
        dmg_die: '1d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing', 
        versatile_die: '',
    },
    'Javelin': {
        atk_ability: 'STR', 
        range: '30/120',
        dmg_die: '1d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Light hammer': {
        atk_ability: 'STR', 
        range: '20/60',
        dmg_die: '1d4', 
        dmg_ability: 'STR', 
        dmg_type: 'Bludgeoning',
        versatile_die: '',
    },
    'Mace': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Bludgeoning',
        versatile_die: '',
    },
    'Quarterstaff': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Bludgeoning',
        versatile_die: '1d8',
    },
    'Sickle': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d4', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing',
        versatile_die: '',
    },
    'Spear': {
        atk_ability: 'STR', 
        range: '20/60',
        dmg_die: '1d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Piercing',
        versatile_die: '1d8',
    },
    'Light crossbow': {
        atk_ability: 'DEX', 
        range: '80/320',
        dmg_die: '1d8', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Dart': {
        atk_ability: 'DEX', 
        range: '20/60',
        dmg_die: '1d4', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Shortbow': {
        atk_ability: 'DEX', 
        range: '80/320',
        dmg_die: '1d6', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Sling': {
        atk_ability: 'DEX', 
        range: '30/120',
        dmg_die: '1d4', 
        dmg_ability: 'DEX', 
        dmg_type: 'Bludgeoning',
        versatile_die: '',
    },
    'Battleaxe': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d8', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing',
        versatile_die: '1d10',
    },
    'Flail': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d8', 
        dmg_ability: 'STR', 
        dmg_type: 'Bludgeoning',
        versatile_die: '',
    },
    'Glaive': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d10', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing',
        versatile_die: '',
    },
    'Greataxe': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d12', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing',
        versatile_die: '',
    },
    'Greatsword': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '2d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing',
        versatile_die: '',
    },
    'Halberd': {
        atk_ability: 'STR', 
        range: 'Reach',
        dmg_die: '1d10', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing',
        versatile_die: '',
    },
    'Lance': {
        atk_ability: 'STR', 
        range: 'Reach',
        dmg_die: '1d12', 
        dmg_ability: 'STR', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Longsword': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d8', 
        dmg_ability: 'STR', 
        dmg_type: 'Slashing',
        versatile_die: '1d10',
    },
    'Maul': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '2d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Bludgeoning',
        versatile_die: '',
    },
    'Morningstar': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d8', 
        dmg_ability: 'STR', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Pike': {
        atk_ability: 'STR', 
        range: 'Reach',
        dmg_die: '1d10', 
        dmg_ability: 'STR', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Rapier': {
        atk_ability: 'DEX', 
        range: '',
        dmg_die: '1d8', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Scimitar': {
        atk_ability: 'DEX', 
        range: '',
        dmg_die: '1d6', 
        dmg_ability: 'DEX', 
        dmg_type: 'Slashing',
        versatile_die: '',
    },
    'Shortsword': {
        atk_ability: 'DEX', 
        range: '',
        dmg_die: '1d6', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Trident': {
        atk_ability: 'STR', 
        range: '20/60',
        dmg_die: '1d6', 
        dmg_ability: 'STR', 
        dmg_type: 'Piercing',
        versatile_die: '1d8',
    },
    'War pick': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d8', 
        dmg_ability: 'STR', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Warhammer': {
        atk_ability: 'STR', 
        range: '',
        dmg_die: '1d8', 
        dmg_ability: 'STR', 
        dmg_type: 'Bludgeoning',
        versatile_die: '1d10',
    },
    'Whip': {
        atk_ability: 'DEX', 
        range: 'Reach',
        dmg_die: '1d4', 
        dmg_ability: 'DEX', 
        dmg_type: 'Slashing',
        versatile_die: '',
    },
    'Blowgun': {
        atk_ability: 'DEX', 
        range: '25/100',
        dmg_die: '1d1', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Hand crossbow': {
        atk_ability: 'DEX', 
        range: '30/120',
        dmg_die: '1d6', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Heavy crossbow': {
        atk_ability: 'DEX', 
        range: '100/400',
        dmg_die: '1d10', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Longbow': {
        atk_ability: 'DEX', 
        range: '150/600',
        dmg_die: '1d8', 
        dmg_ability: 'DEX', 
        dmg_type: 'Piercing',
        versatile_die: '',
    },
    'Net': {
        atk_ability: 'DEX', 
        range: '5/15',
        dmg_die: '', 
        dmg_ability: 'DEX', 
        dmg_type: 'Special',
        versatile_die: '',
    },
}